config/routes.rb
Rails.application.routes.draw do
  
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users

  root to: 'welcome#index'

  get 'welcome/show'

  # namespace :admin do
  #   resources :admins
  # end


  resources :categories do
    resources :articles, shallow: true do
      resources :comments
    end
  end
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  default_scope { order(created_at: :desc) }

  belongs_to :category
  belongs_to :user

  has_many :comments, dependent: :destroy

  validates :title, presence: true
  validates :announcement, presence: true
  validates :body, presence: true

  def moder
    self.approved == true
  end
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :articles, dependent: :destroy

  validates :title, presence: true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
  belongs_to :user

  validates :body, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :articles, dependent: :destroy
  has_many :comments, dependent: :destroy

  validates :profilename, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:profilename, :email, :password, :password_confirmation])
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  # before_action :authenticate_user!
    def index
    #   @categories = Category.all        
    end

    def new
      @category = Category.find(params[:category_id])
      # @article = Article.new
      @article = @category.articles.new
    end

    def show
      @article = Article.find(params[:id])
      # @article = @category.articles.new
    end

    def create
      @category = Category.find(params[:category_id])
      @article = @category.articles.new(articles_params)
      @article.user = current_user

      if @article.save
        redirect_to category_path(@category), notice: "Вы создали статью, она появится тут когда пройдет модерацию"
      else
        render :new
      end
    end

    def destroy
      @article = Article.find(params[:id])
      @article.destroy
      redirect_to category_path(@article.category)
      
      
    end

    private

    def articles_params
      params.require(:article).permit(:title, :body, :announcement)
    end
  end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
    # @category = Category.new        
  end
  def show
    @category = Category.find(params[:id])
    # @article = @category.articles.new
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(categories_params)
    if @category.save
      redirect_to category_path(@category)
    else
      render :new
    end
  end

  def categories_params
    params.require(:category).permit(:title)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    
  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy 
    redirect_to article_path(@comment.article)
  end

  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.new(comment_params.merge(user: current_user))
    @comment.save

    if @comment.save
      redirect_to article_path(@article)
    else
      render 'articles/show'
    end
  end

    private

  def comment_params
    params.require(:comment).permit(:body)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @categories = Category.all
  end

  def show
    if @category = Category.find_by("id = ?", params[:category][:category_id])
      redirect_to category_path(@category)
    else 
      redirect_to root_path, notice: "Нужно выбрать категорию"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/_article.html.slim
- if article.moder
  =content_tag(:div, class: "article-#{article.id}", id: article.id)
    p = link_to article.title, article_path(article)

app/views/articles/_form.html.slim
= render 'shared/errors', resource: @article

= form_with model: [@category, @article] do |form| 
  p
    = form.label :title
    = form.text_field :title
  p
    = form.label :announcement
    = form.text_field :announcement
  p
    = form.label :body
    = form.text_field :body

  = form.submit 'Create Article' 

app/views/articles/new.html.slim
= render 'form'

app/views/articles/show.html.slim
p= @article.title

-if @article.user.id ||= current_user.id
  p= link_to "Delete article", article_path(@article), method: :delete

h1"Comments"


.comment
  = render @article.comments
  
  h1 "Create new comment"
  = render 'comments/form', resource: @article

app/views/categories/_category.html.slim
p = link_to category.title, category_path(category)

app/views/categories/index.html.slim
.categories
  = render @categories

-if user_signed_in?
  h1 "Create new category"
  p = link_to 'Create New Category', new_category_path

app/views/categories/new.html.slim
  = render 'shared/errors', resource: @category
  
  h3 Create new Category
  = form_with model: [@category] do |form| 
    p
      = form.label :title 
      = form.text_field :title
    p     
      = form.submit 'Create'

app/views/categories/show.html.slim
p= @category.title
p= render @category.articles


-if user_signed_in?
  p= link_to "Create new article", new_category_article_path(@category)

app/views/comments/_comment.html.slim
= render 'shared/errors', resource: comment

p = comment.body

- if comment.persisted? && comment.user == current_user
  p= link_to "Delete comment", comment_path(comment), method: :delete

app/views/comments/_form.html.slim
= form_with model: [resource, Comment.new] do |form| 
  p
    = form.label :body
    = form.text_field :body
  p
    = form.submit 'Create comment'

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>NewsPortal</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/shared/_errors.html.slim
- if resource&.errors.present?
  b= "#{resource.errors.count} error(s) detected: "
  ul
    -resource.errors.full_messages.each do |message|
      li= message

app/views/shared/_nav.html.slim
.div
  .text-center
    h1 "Welcome News Portal"
    -if user_signed_in?
      h2 "Hello - #{current_user.profilename}"

  .nav-user
    p= link_to 'Log in', new_user_session_path
    p= link_to 'Sign out', destroy_user_session_path, method: :delete
    p= link_to 'Sigh up', new_user_registration_path

app/views/welcome/index.html.slim
h1 "Welcome News Portal"

p = link_to 'You admin?', new_admin_user_session_path

- if user_signed_in?
  h2 "Hello - #{current_user.profilename}"

.category_select
  = form_for :category, url: {action: "show"}, html: {method: "get"} do |f|
    p
      = f.select :category_id, options_for_select(@categories.collect { |category| [category.title, category.id] }), prompt: "Выберите пожалуйста категорию"
    p
      = f.submit "Go!"

p = link_to 'All categories', categories_path
p = link_to 'Log in', new_user_session_path
p = link_to 'Sign out', destroy_user_session_path, method: :delete
p = link_to 'Sigh up', new_user_registration_path